-- upgrade --
CREATE TABLE IF NOT EXISTS "tokens" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "token" VARCHAR(30) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "modified_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "user_id" INT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE
);;
CREATE TABLE IF NOT EXISTS "users" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "username" VARCHAR(30) NOT NULL UNIQUE,
    "first_name" VARCHAR(30),
    "last_name" VARCHAR(30),
    "password" VARCHAR(120) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "modified_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "token";
-- downgrade --
DROP TABLE IF EXISTS "tokens";
DROP TABLE IF EXISTS "users";
